### ISSUE TITLE
Push new release to Ansible Galaxy

### ISSUE THREAD

**Issue by berendt** [dresden-weekly/ansible-network-interfaces#15]
The role published on Ansible Galaxy does not support bonding devices at the moment. Plesae push a new release to Ansible Galaxy.

**Comment by arBmind** [comment]
@berendt i know but having the Ansible 2.0 issue still open, blocks any new release.

I will try to do some work here during the Dresden weekly next week.

**Comment by arBmind** [comment]
released 1.0 version
