### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by davidmnoriega** [dresden-weekly/ansible-network-interfaces#36]
Great role, but I have some questions on the readme.
1. What does `network` do? Its not a keyword in `/etc/network/interfaces`
2. `subnets` confused me until I read through the template. The readme should explain a bit on its use
3. No mention of CIDR support. Reading, and testing, the template code I realize I didn't have to use `netmask` but instead able to use CIDR notation in `address` to specify both. This was also further confused with what purpose `subnets` fulfill.

**Comment by arBmind** [comment]
Hey @davidmnoriega. I am happy that you like our role.

Regarding your questions.
1. network is not used most of the time, but it is or was a keyword. Searching for it, I found: http://www.cyberciti.biz/faq/setting-up-an-network-interfaces-file/
2. `subnets` is a concept I came up with. We needed this for multiple ip addresses. I confess that this should be better documented.
3. CIDR support is nothing we invented here. But it would not do harm to add an example for that in the readme.

Some good suggestions. I would be more than happy to merge a PR for that.
