### ISSUE TITLE
Jinja2 2.9.x broken

### ISSUE THREAD

**Issue by berendt** [dresden-weekly/ansible-network-interfaces#46]
Looks like Jinja 2.9.x introduced some issue with the ```groupby``` filter used in the ```configurations``` task:

```
TASK [network-interfaces : configurations] *************************************
 [WARNING]: Exception in safe_eval() on expr: [_GroupTuple(grouper=u'eth0', ..., "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute 'device'"}
```

Tested with Ansible 2.2.0.0 and Jinja2 2.9.3.

**Comment by tersmitten** [comment]
I think they are already resolved in development

**Comment by tersmitten** [comment]
https://github.com/ansible/ansible/pull/20014

**Comment by NicolasLM** [comment]
I confirm that it is fixed, ansible now specifies jinja2 < 2.9.

**Comment by berendt** [comment]
@NicolasLM In master branch or in all current stable releases?

**Comment by tersmitten** [comment]
* https://github.com/ansible/ansible/compare/v2.1.3.0-1...v2.1.4.0-1
* https://github.com/ansible/ansible/compare/v2.2.0.0-1...v2.2.1.0-1

**Comment by jangrewe** [comment]
Thanks for this issue. I was able to fix it on my machine by removing the pip-installed version of Jinja2, so that Ubuntu's version is used. Didn't know what too look for, before i found this issue.

**Comment by arBmind** [comment]
Ok, so this is not an issue of this module, but Ansible itself?

Can we close it here?

**Comment by tersmitten** [comment]
Yes, I would say so

**Comment by arBmind** [comment]
Ok, I close the issue.
